[package]
name = "bjj_scoreboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
crossterm = "0.26.1"
eframe = "0.22.0"
egui_extras = "0.22.0"
egui_grid = "0.2.0"
